version: 2.1
jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: rt-api-test-test

    steps:
      - checkout

      - run:
          name: Set up Ruby
          command: |
            sudo apt-get update -y
            sudo apt-get install -y ruby-full
            gem install bundler

      - run:
          name: Install dependencies
          command: |
            bundle install --jobs 4 --retry 3

      - run:
          name: Install PostgreSQL
          command: |
            sudo apt-get install -y postgresql postgresql-contrib

      - run:
          name: Start PostgreSQL Service
          command: sudo service postgresql start

      - run:
          name: Check PostgreSQL Service Status
          command: |
            service postgresql status

      - run:
          name: Make bin/rails executable
          command: chmod +x bin/rails

      - run:
          name: Create DB
          environment:
            RAILS_ENV: test
            DATABASE_URL: postgres://postgres:root@localhost:5432/rt-api-test-test
          command: |
            bin/rails db:create
            bin/rails db:schema:load

      - run:
          name: Run Tests
          environment:
            RAILS_ENV: test
            DATABASE_URL: postgres://postgres:root@localhost:5432/rt-api-test-test
          command: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - test

