version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0
  postgres: circleci/postgres@1.2.0

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.2.2
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: rt-api-test-test

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            gem install bundler
            bundle install --jobs 4 --retry 3

      - run:
          name: Set up Database
          command: |
            bundle exec rails db:create RAILS_ENV=test
            bundle exec rails db:schema:load RAILS_ENV=test

      - run:
          name: Run Tests
          command: |
            bundle exec rspec

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build_and_test

