version: 2.1
jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: rt-api-test-test
    steps:
      - checkout

      - run:
          name: Set Environment Variables
          command: |
            echo 'export RAILS_ENV=production' >> $BASH_ENV
            echo 'export SECRET_KEY_BASE=your_secret_key_here' >> $BASH_ENV
            echo 'export ANOTHER_VARIABLE=value' >> $BASH_ENV

      - run:
          name: Configure sudo to not prompt for a password
          command: |
            echo "circleci ALL=(ALL:ALL) NOPASSWD:/usr/bin/psql" | sudo tee -a /etc/sudoers.d/circleci
            sudo chmod 440 /etc/sudoers.d/circleci

      - run:
          name: Set up Ruby
          command: |
            sudo apt-get update -y
            sudo apt-get install -y ruby-full
            gem install bundler

      - run:
          name: Install dependencies
          command: |
            bundle install --jobs 4 --retry 3

      - run:
          name: Install PostgreSQL
          command: |
            sudo apt-get install -y postgresql postgresql-contrib

      - run:
          name: Start PostgreSQL Service
          command: sudo service postgresql start

      - run:
          name: Change PostgreSQL User Password
          command: |
            sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'root';"

      - run:
          name: Check PostgreSQL Service Status
          command: |
            service postgresql status

      - run:
          name: Make bin/rails executable
          command: chmod +x bin/rails

      - run:
          name: Create DB
          environment:
            RAILS_ENV: test
            DATABASE_URL: postgres://postgres:root@localhost:5432/rt-api-test-test
          command: |
            bin/rails db:create
            bin/rails db:schema:load

      - run:
          name: Run Tests
          environment:
            RAILS_ENV: test
            DATABASE_URL: postgres://postgres:root@localhost:5432/rt-api-test-test
          command: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - test

