version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  postgres: circleci/postgres@1.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2  # Ruby version
      - image: circleci/postgres:latest  # PostgreSQL version
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: rt-api-test-test

    working_directory: ~/repo

    steps:
      - checkout

      - ruby/install-deps

      - run: 
          name: Set up Database
          command: |
            sudo apt-get install libpq-dev
            bundle exec rails db:create db:schema:load

      - run:
          name: Run Tests
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
