default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'root' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>

development:
  <<: *default
  database: rt-api-test

test:
  <<: *default
  database: rt-api-test-test

production:
  <<: *default
  database: restaurant_api_production
  username: postgresql
  password: <%= ENV["RESTAURANT_API_DATABASE_PASSWORD"] %>
  port: 5432
